const proxy = require('http-proxy-middleware')
const express = require('express')
const path = require('path')
const app = express()
const compression = require('compression')
const helmet = require('helmet')
app.use(compression())
app.use(helmet())
app.use(express.static(path.resolve(__dirname, '../client/build')))
app.use('/api', proxy({ target: `http://localhost:${process.env.NODE_ENV === 'production' ? 5001 : 5000}/` }))
app.get('/*', (req, res) => res.sendFile(path.resolve(__dirname, '../client/build/index.html')))
app.listen(process.env.PORT)
